-- Script de datos de prueba para tests de lista de tareas
-- Tabla: TAREA

CREATE TABLE IF NOT EXISTS TAREA (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ASUNTO VARCHAR(255) NOT NULL,
    FECHA DATE NOT NULL,
    ESTADO VARCHAR(20) NOT NULL
);

-- Datos de prueba para tests de obtener lista de tareas
INSERT INTO TAREA (ASUNTO, FECHA, ESTADO) VALUES 
    ('Terminar informe mensual', DATE '2025-02-20', 'pendiente'),
    ('Revisar código del módulo auth', DATE '2025-02-18', 'en_progreso'),
    ('Actualizar documentación API', DATE '2025-02-15', 'completada');